// AI-voice heuristic detector (Phase 2 of the AI Voice feature).
//
// Pure + deterministic + explainable: given a show's metadata (name, description,
// host, RSS <generator>) and a sample of its episodes (titles, dates, durations),
// it scores four red flags and returns a plain-English reason for each hit. It
// NEVER decides anything public — its output becomes a "Suspected" flag for a
// human to confirm (see /api/admin/scan-ai-voices + lib/voice.js).
//
// Weights are tuned so the strong, specific signals (a known AI-tool generator
// tag, or explicit "AI-generated" wording) can flag on their own, while the soft
// signals (no host, machine-like cadence) only ever corroborate — they can't
// flag a show by themselves. That bias is deliberate: false positives here are
// the whole risk.

// Known AI podcast generators / TTS tools. Matched case-insensitively as
// substrings against the RSS <generator> tag (and, loosely, author/description).
export const AI_GENERATOR_TOOLS = [
  'wondercraft', 'notebooklm', 'notebook lm', 'podcastle', 'elevenlabs', 'eleven labs',
  'play.ht', 'playht', 'jellypod', 'speechki', 'autopod', 'podcast.ai', 'aipod',
  'recast', 'listenwave', 'podgenai', 'podcastworld', 'poddy', 'monica ai',
  'audiocleaner', 'coqui', 'murf.ai', 'murf ', 'resemble.ai', 'well said labs',
];

// Phrases in title/description/author that openly state synthetic narration.
export const AI_WORDING = [
  'ai-generated', 'ai generated', 'generated by ai', 'ai-narrated', 'ai narrated',
  'narrated by ai', 'ai voice', 'ai-voiced', 'synthetic voice', 'synthetic narration',
  'text-to-speech', 'text to speech', 'tts voice', 'ai host', 'ai-hosted', 'ai co-host',
  'powered by ai', 'ai-powered podcast', 'artificial intelligence voice',
  'this podcast was generated', 'created with ai', 'voiced by ai', 'computer-generated voice',
];

// Weights (0–100 scale). Strong signals ≥ FLAG_THRESHOLD flag alone.
const W = {
  generator: 65,   // RSS generator names a known AI tool — strongest
  wording:   55,   // openly says AI/synthetic/TTS
  wordingWeak: 25, // a single soft phrase only in one place
  noHost:    18,   // no named human host + boilerplate copy
  cadence:   20,   // firehose cadence + uniform durations (content-mill tell)
};

export const FLAG_THRESHOLD = 50; // heuristic score at/above which we suspect

function norm(s) { return (s || '').toString().toLowerCase(); }

// —— individual signals ——————————————————————————————————————————————

export function matchGeneratorTool(generator) {
  const g = norm(generator);
  if (!g) return null;
  return AI_GENERATOR_TOOLS.find(t => g.includes(t)) || null;
}

export function matchAiWording(text) {
  const t = norm(text);
  if (!t) return [];
  return AI_WORDING.filter(p => t.includes(p));
}

// A named human host looks like a person: has a space, isn't a URL/brand, isn't
// obviously a tool. Very rough — only used as a soft corroborating signal.
function looksLikeToolAuthor(author) {
  const a = norm(author);
  if (!a) return true; // no author at all counts toward "no human host"
  if (matchGeneratorTool(a)) return true;
  if (/\b(ai|bot|studio|media|network|podcast|automated|daily)\b/.test(a) && !/\s/.test(a.replace(/\b(ai|bot)\b/, ''))) return false;
  return false;
}

// Machine-like cadence: many episodes, very short median gap (≈ daily or faster)
// AND tightly-clustered durations (auto-generated digests are near-identical
// length). Needs a real sample to fire.
function cadenceSignal(episodes) {
  const eps = (episodes || []).filter(e => e && e.published_at);
  if (eps.length < 8) return null;
  const dates = eps.map(e => new Date(e.published_at).getTime()).filter(n => !isNaN(n)).sort((a, b) => b - a);
  if (dates.length < 8) return null;
  const gapsDays = [];
  for (let i = 1; i < dates.length; i++) gapsDays.push((dates[i - 1] - dates[i]) / 86400000);
  const medGap = median(gapsDays);
  // durations
  const durs = eps.map(e => e.duration_seconds).filter(n => typeof n === 'number' && n > 0);
  let uniform = false;
  if (durs.length >= 8) {
    const m = median(durs);
    const spread = m ? (stdev(durs) / m) : 1; // coefficient of variation
    uniform = spread < 0.15; // durations within ~15% of each other
  }
  if (medGap <= 1.2 && uniform) {
    return `publishes ≈${medGap < 1.05 ? 'daily or faster' : 'daily'} with near-uniform episode lengths (auto-digest pattern)`;
  }
  return null;
}

function median(arr) {
  if (!arr.length) return 0;
  const s = [...arr].sort((a, b) => a - b);
  const mid = Math.floor(s.length / 2);
  return s.length % 2 ? s[mid] : (s[mid - 1] + s[mid]) / 2;
}
function stdev(arr) {
  if (arr.length < 2) return 0;
  const m = arr.reduce((a, b) => a + b, 0) / arr.length;
  return Math.sqrt(arr.reduce((a, b) => a + (b - m) ** 2, 0) / arr.length);
}

// —— composite ————————————————————————————————————————————————————————

// Returns { score, suspected, flags:[{signal,weight,detail}], voiceType }.
// `episodes` is a sample of the show's episodes (title/description/published_at/
// duration_seconds). `generator` is the RSS <generator> tag text.
export function scoreShow({ name, description, author, generator, episodes = [] } = {}) {
  const flags = [];

  const tool = matchGeneratorTool(generator);
  if (tool) flags.push({ signal: 'generator', weight: W.generator, detail: `RSS generator is an AI podcast tool ("${tool}")` });

  // Wording across the show's own text + a sample of episode text.
  const showText = [name, description, author].filter(Boolean).join('  ');
  const epText = episodes.map(e => `${e.title || ''} ${e.description || ''}`).join('  ');
  const showHits = matchAiWording(showText);
  const epHits = matchAiWording(epText);
  const allHits = [...new Set([...showHits, ...epHits])];
  if (allHits.length) {
    const strong = showHits.length > 0 || allHits.length >= 2;
    flags.push({
      signal: 'wording', weight: strong ? W.wording : W.wordingWeak,
      detail: `text mentions ${allHits.slice(0, 3).map(h => `"${h}"`).join(', ')}${allHits.length > 3 ? '…' : ''}`,
    });
  }

  // Soft: no human host + boilerplate-ish (short/empty) description.
  const boiler = norm(description).length < 60;
  if (looksLikeToolAuthor(author) && boiler) {
    flags.push({ signal: 'noHost', weight: W.noHost, detail: 'no named human host and a thin/boilerplate description' });
  }

  const cadence = cadenceSignal(episodes);
  if (cadence) flags.push({ signal: 'cadence', weight: W.cadence, detail: cadence });

  // Score = capped sum, but soft signals alone are capped below threshold so they
  // can only corroborate, never flag on their own.
  const strongScore = flags.filter(f => f.signal === 'generator' || f.signal === 'wording').reduce((a, f) => a + f.weight, 0);
  const softScore = flags.filter(f => f.signal === 'noHost' || f.signal === 'cadence' || (f.signal === 'wording' && f.weight === W.wordingWeak)).reduce((a, f) => a + f.weight, 0);
  let score = Math.min(100, strongScore + softScore);
  // Guard: if there is NO strong signal, cap below the flag threshold so soft
  // signals never suspect a show on their own.
  const hasStrong = flags.some(f => (f.signal === 'generator') || (f.signal === 'wording' && f.weight >= W.wording));
  if (!hasStrong) score = Math.min(score, FLAG_THRESHOLD - 1);

  return {
    score,
    suspected: score >= FLAG_THRESHOLD,
    flags,
    voiceType: 'AI-generated',
  };
}
